#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ -f $OPENSHIFT_TMP_DIR/openmeap.db ]
then
exit 0
else
cp -rf $OPENSHIFT_REPO_DIR/openmeap.db $OPENSHIFT_TMP_DIR
cp -rf $OPENSHIFT_REPO_DIR/57c896f5e47c39a37b051f5bbfddd71e $OPENSHIFT_DATA_DIR
cp -rf $OPENSHIFT_REPO_DIR/57c896f5e47c39a37b051f5bbfddd71e.zip $OPENSHIFT_DATA_DIR

fi