#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ -f $OPENSHIFT_DATA_DIR/openmeap.db ]
then
  export OPENMEAP_JDBC_URL=jdbc:sqlite:/$OPENSHIFT_DATA_DIR/openmeap.db
else
export OPENMEAP_JDBC_URL=jdbc:sqlite:/$OPENSHIFT_DATA_DIR/openmeap.db
cp -rf $OPENSHIFT_REPO_DIR/openmeap.db $OPENSHIFT_DATA_DIR
cp -rf $OPENSHIFT_REPO_DIR/258f00cb69d88aebc3da66b890d0b515 $OPENSHIFT_DATA_DIR
cp -rf $OPENSHIFT_REPO_DIR/258f00cb69d88aebc3da66b890d0b515.zip $OPENSHIFT_DATA_DIR

fi