#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ -f $OPENSHIFT_TMP_DIR/openmeap.db ]
then
exit 0
else
cp -rf $OPENSHIFT_REPO_DIR/openmeap.db $OPENSHIFT_TMP_DIR
cp -rf $OPENSHIFT_REPO_DIR/57c896f5e47c39a37b051f5bbfddd71e $OPENSHIFT_DATA_DIR
cp -rf $OPENSHIFT_REPO_DIR/57c896f5e47c39a37b051f5bbfddd71e.zip $OPENSHIFT_DATA_DIR

fi